<?php

/**
 * @file
 * Install, update and uninstall functions for the number module.
 */

/**
 * Implements hook_field_schema().
 */
function artisinal_field_schema($field) {
  switch ($field['type']) {
    case 'artisinal_integer' :
      $columns = array(
        'value' => array(
          'type' => 'int',
          'not null' => FALSE
        ),
      );
      break;
  }
  return array(
    'columns' => $columns,
  );
}
